const clinciArray = [
	{
		id: 1,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Union Family Health Center',
		workingDay: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Carymouth , Hallmark Clinic',
		rating: '1.9',
		clinicPhoneNumber: '+99557799700',
		clinicEmail: 'atcare@optimo.com',
		sale: 10,
	},
	{
		id: 2,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingday: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 20,
	},
	{
		id: 3,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingday: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 30,
	},
	{
		id: 4,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingday: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 40,
	},

	{
		id: 5,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Union Family Health Center',
		workingDay: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Carymouth , Hallmark Clinic',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 70,
	},
	{
		id: 6,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Healing Helpers Medical Group',
		workingDay: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 80,
	},
	{
		id: 7,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingDay: 'Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Carymouth , Hallmark Clinic',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 90,
	},
	{
		id: 8,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingday: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 100,
	},
	{
		id: 9,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Progress Medical Clinic',
		workingday: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 50,
	},
	{
		id: 10,
		src: '/clinicImage.png',
		alt: 'clinic image',
		clinicName: 'Healing Helpers Medical Group',
		workingDay: ' Monday - Friday',
		workingHours: '10:00 - 17:00',
		weekendWorkingDay: 'Saturday - Sunday',
		weekendWorkingHours: '10:00 - 14:00',
		clinicAddress: 'Tbilisi , Chachava str.1',
		rating: '4.9',
		clinicPhoneNumber: '+995577997799',
		clinicEmail: 'atcare@gmail.com',
		sale: 60,
	},
];

export default clinciArray;
