const buyCardData = [
  {
    id: "0",
    features: "Feature",
    silver: "Silver",
    Gold: "Gold",
    platinium: "Platinium",
  },
  {
    id: "1",
    features: "Number of Invoices",
    silver: "5",
    Gold: "5",
    platinium: "Unlimited",
  },
  {
    id: "2",
    features: "Number of Customers",
    src: "/qaIcon.svg",
    silver: "2",
    Gold: "10",
    platinium: "Unlimited",
  },
  {
    id: "3",
    features: "Number of Products",
    silver: "10",
    Gold: "100",
    platinium: "Unlimited",
  },
  {
    id: "4",
    features: "Number of Products",
    silver: "10",
    Gold: "100",
    platinium: "Unlimited",
  },
  {
    id: "5",
    features: "Recuring Inoices",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "6",
    features: "Team Members (users)",
    silver: "1",
    Gold: "2",
    platinium: "Unlimited",
  },
  {
    id: "7",
    features: "Multiple businesses",
    src: "/activeQaIcon.svg",
    silver: "1",
    Gold: "2",
    platinium: "Unlimited",
  },
  {
    id: "8",
    features: "Financil Dashboard",
    silver: "emptyIcon",
    Gold: "Full",
    platinium: "Full",
  },
  {
    id: "9",
    features: "Data Import/Export",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "10",
    features: "Old invoice access",
    silver: "6 month",
    Gold: "Unlimited",
    platinium: "Unlimited",
  },
  {
    id: "32",
    features: "",
    silver: "",
    Gold: "",
    platinium: "",
  },
  {
    id: "11",
    features: "",
    silver: "Silver",
    Gold: "Gold",
    platinium: "Platinium",
  },
  {
    id: "12",
    features: "SMS reminders",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "13",
    features: "RS integrations",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "14",
    features: "TBC integration",
    silver: "icon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "15",
    features: "Accept online payments",
    silver: "icon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "29",
    features: "",
    silver: "",
    Gold: "",
    platinium: "",
  },
  {
    id: "16",
    features: "",
    silver: "Silver",
    Gold: "Gold",
    platinium: "Platinium",
  },
  {
    id: "17",
    features: "No invoice.ge branding",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "18",
    features: "Customize invoice template",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "19",
    features: "Send emails from your domain",
    silver: "emptyIcon",
    Gold: " emptyIcon",
    platinium: "icon",
  },
  {
    id: "30",
    features: "",
    silver: "",
    Gold: "",
    platinium: "",
  },
  {
    id: "20",
    features: "",
    silver: "Silver",
    Gold: "Gold",
    platinium: "Platinium",
  },
  {
    id: "21",
    features: "Invoice Tracking",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "22",
    features: "Multi Currency invoice",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "31",
    features: "",
    silver: "",
    Gold: "",
    platinium: "",
  },
  {
    id: "23",
    features: "",
    silver: "Silver",
    Gold: "Gold",
    platinium: "Platinium",
  },
  {
    id: "24",
    features: "Live Chat 24/7",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "25",
    features: "API access",
    silver: "emptyIcon",
    Gold: "emptyIcon",
    platinium: "icon",
  },
  {
    id: "26",
    features: "All Current and Future invoice.ge features",
    silver: "emptyIcon",
    Gold: "emptyIcon",
    platinium: "icon",
  },
  {
    id: "27",
    features: "SSI Encryption",
    silver: "icon",
    Gold: "icon",
    platinium: "icon",
  },
  {
    id: "28",
    features: "Two Factor Auth",
    silver: "emptyIcon",
    Gold: "icon",
    platinium: "icon",
  },
];

export default buyCardData;
