export async function getData(url) {
	try {
		const res = await fetch(url, {
			headers: {
				'Content-Type': 'application/json',
				// "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzRUNseXdhVnNxOURBMU1oMElNLTVFTUNsRU5WM1FMTnhuNlh1bDJoOVBnIn0.eyJleHAiOjE2Njk2NjI4NTEsImlhdCI6MTY2OTYyNjg5MSwiYXV0aF90aW1lIjoxNjY5NjI2ODUxLCJqdGkiOiI0ZTIyY2VhYS0zYzUwLTQ2OGUtOTU4Ni1jNGNmMzhjMzU5MmUiLCJpc3MiOiJodHRwczovL2F1dGgucGlydmVsaS5nZS9yZWFsbXMveHJhY29vbi1kZW1vIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6IjIzZTNjZmYzLTA1MDktNGVmMS04YzI3LWYzYzJkYzk0ZjRlNCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNzLWNhcnQiLCJzZXNzaW9uX3N0YXRlIjoiYTM3NDZmMTEtMTI1MS00YmYyLTllMjYtMWUxYzBiMmE1ODNiIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXhyYWNvb24tZGVtbyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJhMzc0NmYxMS0xMjUxLTRiZjItOWUyNi0xZTFjMGIyYTU4M2IiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInVzZXJfaWQiOiIyM2UzY2ZmMy0wNTA5LTRlZjEtOGMyNy1mM2MyZGM5NGY0ZTQiLCJuYW1lIjoiaXJha2xpIHphbmV0dHUiLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJkc2FkYUBnbWFpbC5jb20iLCJnaXZlbl9uYW1lIjoiaXJha2xpIiwiZmFtaWx5X25hbWUiOiJ6YW5ldHR1IiwiZW1haWwiOiJkc2FkYUBnbWFpbC5jb20ifQ.VP9rR6gViiopXXuT0tb9tqy5jJF6kzk8N-1pFIDZ4Qd27pXtIn_uPnHWabwy67BMkNwuekgVyO6a91YI8OiiCzrR1eG94EaTIcIKD9yxaqrg9BBWKbry1t3SbaWE5xJSSoueD3uqrP2i7kyROKKhUdwQ7pJ9gsf1TrqWooaunjClvJCYP_w1yKF9SndFCImfmvlCQwm8vcZPihlQvlcJGyLuUL5KYQMPnxl30BIysnN54mp7GY9m434G86hlBu22A4JKwiYjLzlyg62yPgE22O0BeBQ2dtGEZupNqfpkVtEQeDxgj9XKEQ6KVc5D1ynXNu1eU-QIzW9PBvPhdf6soA"
			}
		})
		const response = res.json();

		return response
	}catch(error){
		console.log(error)
	}
}


export async function postData(url = '', data = {}, method) {
	const response = await fetch(url, {
		method: method, // *GET, POST, PUT, DELETE, etc.
		mode: 'cors', // no-cors, *cors, same-origin
		cache: 'no-cache', // *default, no-cache, reload, force-cache, only-if-cached
		credentials: 'same-origin', // include, *same-origin, omit
		headers: {
			'Content-Type': 'application/json',
			// "Authorization": "Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJzRUNseXdhVnNxOURBMU1oMElNLTVFTUNsRU5WM1FMTnhuNlh1bDJoOVBnIn0.eyJleHAiOjE2NjkxNDM1NzIsImlhdCI6MTY2OTEwNzU4NSwiYXV0aF90aW1lIjoxNjY5MTA3NTcyLCJqdGkiOiI1MTY3YTk0My1kZmIzLTQ2N2UtODFjZC1hNzA0MDUyZjk4NmQiLCJpc3MiOiJodHRwczovL2F1dGgucGlydmVsaS5nZS9yZWFsbXMveHJhY29vbi1kZW1vIiwiYXVkIjoiYWNjb3VudCIsInN1YiI6ImY4OWFjM2M2LTk2MTItNDY4YS1hYzk4LWM3ZWVkN2VjYzExZSIsInR5cCI6IkJlYXJlciIsImF6cCI6ImNzLWNhcnQiLCJzZXNzaW9uX3N0YXRlIjoiZjUxZWUwY2QtZjNhYS00NDM2LWE2NjUtNzA5NGJhZGY2ZWUxIiwiYWNyIjoiMSIsInJlYWxtX2FjY2VzcyI6eyJyb2xlcyI6WyJkZWZhdWx0LXJvbGVzLXhyYWNvb24tZGVtbyIsIm9mZmxpbmVfYWNjZXNzIiwidW1hX2F1dGhvcml6YXRpb24iXX0sInJlc291cmNlX2FjY2VzcyI6eyJhY2NvdW50Ijp7InJvbGVzIjpbIm1hbmFnZS1hY2NvdW50IiwibWFuYWdlLWFjY291bnQtbGlua3MiLCJ2aWV3LXByb2ZpbGUiXX19LCJzY29wZSI6InByb2ZpbGUgZW1haWwiLCJzaWQiOiJmNTFlZTBjZC1mM2FhLTQ0MzYtYTY2NS03MDk0YmFkZjZlZTEiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInVzZXJfaWQiOiJmODlhYzNjNi05NjEyLTQ2OGEtYWM5OC1jN2VlZDdlY2MxMWUiLCJuYW1lIjoidmF0byBrb2J1bGlhIiwicHJlZmVycmVkX3VzZXJuYW1lIjoidmF0b2tvYnVsaWFAZ21haWwuY29tIiwiZ2l2ZW5fbmFtZSI6InZhdG8iLCJmYW1pbHlfbmFtZSI6ImtvYnVsaWEiLCJlbWFpbCI6InZhdG9rb2J1bGlhQGdtYWlsLmNvbSJ9.VH3qTLgHBGQMNdrrDSFxl72lR75f2OuhiibB-I8q6j8g21DDcxGWTrDPQKDUIuFJVRx-mlz8KIN2n5mJa6l03EtIqYVMPVx2kT0ExhvJgxeiTKp2ZTrKhBRQuNN49Up8QVR-02i1p5HHa2-3t2Z-zNuHkzi_bFgdnGBm7sfHjoX6sgW9BEjDKSmEJk0r0pv1rz26NMSTZn-tzJDQNJqXX36EFHpPqLO6sO93bXOn7VS6jL1dKiPbKEbeSffK9Zsoq4_EIuufKcwht5DZST_WFOoJ4XsFWvXYKZkjB2C_6Kl4oUQI66AqRFMXP0nfj_7--ldVpS-QxIbcwLvqzXsk4g"
			// 'Content-Type': 'application/x-www-form-urlencoded',
		},
		redirect: 'follow', // manual, *follow, error
		referrerPolicy: 'no-referrer', // no-referrer, *no-referrer-when-downgrade, origin, origin-when-cross-origin, same-origin, strict-origin, strict-origin-when-cross-origin, unsafe-url
		body: JSON.stringify(data) // body data type must match "Content-Type" header
	});
	return response.json(); // parses JSON response into native JavaScript objects
}